[package]
name = "rust-dpi"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytes = "1.7.1"
env_logger = "0.11.5"
fast-socks5 = "0.9.6"
io-uring = "0.7.0"
log = "0.4.22"
slab = "0.4.9"
structopt = "0.3.26"
tokio = { version = "1.40.0", features = ["full"] }
tokio-stream = "0.1.15"
tokio-uring = "0.5.0"
